### ISSUE TITLE
Overlays z-index is not high enough for embedding in popups

### ISSUE THREAD

**Issue by AbelVM** [mapillary/mapillary-js#244]
Looks like overlays'
```CSS
z-index: 10;
```
is not enough when embedding the viewer

**mapillary-js version**: latest

### Steps to Reproduce Behavior

 1. Embed the viewer within a Leaflet popup
 2. Open it

### Expected Behavior
The overlays are there

### Actual Behavior
No visible overlays (navigation, attribution, PoV, etc.)

### Workaround:
Just force the Z-index to any value above 99

```CSS
.domRenderer > div {
    z-index: 100 !important; 
}
```
